bundles:
  - 2
files:
  - source: /composeApp/src/commonMain/resources/MR/base/strings.xml
    translation: /composeApp/src/commonMain/resources/MR/%two_letters_code%/strings.xml
  - source: /docs/en/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
