package com.arnyminerz.filamagenta.utils

import androidx.compose.runtime.Composable
import com.arnyminerz.filamagenta.MR
import dev.icerock.moko.resources.compose.stringResource
import dev.icerock.moko.resources.desc.StringDesc

data class Language(val langCode: String) {
    companion object {
        private const val LANG_CODE_SYSTEM = "system"

        val System = Language(LANG_CODE_SYSTEM)
    }

    val localeType: StringDesc.LocaleType = if (langCode == LANG_CODE_SYSTEM)
        StringDesc.LocaleType.System
    else
        StringDesc.LocaleType.Custom(langCode)

    val displayName: String
        @Composable
        get() = if (langCode == LANG_CODE_SYSTEM)
            stringResource(MR.strings.settings_language_system)
    else
            languageCodesRepresentation.getValue(langCode)

    override fun toString(): String = langCode
}

/**
 * Adds the [Language.System] language to the beginning of the list.
 */
fun List<Language>.prefixSystem(): List<Language> = toMutableList().apply { add(0, Language.System) }

val languageCodesRepresentation: Map<String, String> = mapOf(
    "aa" to "Afar",
    "ab" to "Abkhazian",
    "ae" to "Avestan",
    "af" to "Afrikaans",
    "ag" to "Aghuyar",
    "ah" to "Amharic",
    "ak" to "Akan",
    "al" to "Albanian",
    "am" to "Amharic",
    "an" to "Aragonese",
    "ar" to "Arabic",
    "as" to "Assamese",
    "av" to "Avaric",
    "ay" to "Aymara",
    "az" to "Azerbaijani",
    "ba" to "Bashkir",
    "be" to "Belarusian",
    "bg" to "Bulgarian",
    "bh" to "Bihari languages",
    "bi" to "Bislama",
    "bm" to "Bambara",
    "bn" to "Bengali",
    "bo" to "Tibetan",
    "br" to "Breton",
    "bs" to "Bosnian",
    "ca" to "Catalan",
    "ce" to "Chechen",
    "ch" to "Chamorro",
    "ci" to "Chichewa",
    "co" to "Corsican",
    "cr" to "Cree",
    "cs" to "Czech",
    "cu" to "Church Slavic",
    "cv" to "Chuvash",
    "cy" to "Welsh",
    "da" to "Danish",
    "de" to "German",
    "dv" to "Dhivehi",
    "dz" to "Dzongkha",
    "ee" to "Ewe",
    "el" to "Greek",
    "en" to "English",
    "eo" to "Esperanto",
    "es" to "Spanish",
    "et" to "Estonian",
    "eu" to "Basque",
    "fa" to "Persian",
    "ff" to "Fula",
    "fi" to "Finnish",
    "fj" to "Fijian",
    "fo" to "Faroese",
    "fr" to "French",
    "fy" to "West Frisian",
    "ga" to "Irish",
    "gd" to "Scottish Gaelic",
    "ge" to "Georgian",
    "gl" to "Galician",
    "gn" to "Guarani",
    "goh" to "Old High German",
    "grc" to "Ancient Greek",
    "gsw" to "Swiss German",
    "gu" to "Gujarati",
    "gv" to "Manx",
    "ha" to "Hausa",
    "he" to "Hebrew",
    "hi" to "Hindi",
    "ho" to "Hiri Motu",
    "hr" to "Croatian",
    "ht" to "Haitian Creole",
    "hu" to "Hungarian",
    "hy" to "Armenian",
    "hz" to "Herero",
    "ia" to "Interlingua",
    "id" to "Indonesian",
    "ie" to "Interlingue",
    "ig" to "Igbo",
    "ii" to "Sichuan Yi",
    "ik" to "Inupiaq",
    "io" to "Ido",
    "is" to "Icelandic",
    "it" to "Italian",
    "iu" to "Inuktitut",
    "ja" to "Japanese",
    "jv" to "Javanese",
    "ka" to "Georgian",
    "kg" to "Kongo",
    "ki" to "Kikuyu",
    "kj" to "Kuanyama",
    "kk" to "Kazakh",
    "kl" to "Kalaallisut",
    "km" to "Khmer",
    "kn" to "Kannada",
    "ko" to "Korean",
    "kr" to "Kanuri",
    "ks" to "Kashmiri",
    "ku" to "Kurdish",
    "kv" to "Komi",
    "kw" to "Cornish",
    "ky" to "Kirghiz",
    "la" to "Latin",
    "lb" to "Luxembourgish",
    "lg" to "Ganda",
    "li" to "Limburgish",
    "ln" to "Lingala",
    "lo" to "Lao",
    "lt" to "Lithuanian",
    "lu" to "Luba-Katanga",
    "lv" to "Latvian",
    "mg" to "Malagasy",
    "mh" to "Marshallese",
    "mi" to "Maori",
    "mk" to "Macedonian",
    "ml" to "Malayalam",
    "mn" to "Mongolian",
    "mo" to "Moldavian",
    "mr" to "Marathi",
    "ms" to "Malay",
    "mt" to "Maltese",
    "my" to "Burmese",
    "na" to "Nauru",
    "nb" to "Bokmål, Norwegian",
    "nd" to "North Ndebele",
    "ne" to "Nepali",
    "ng" to "Ndonga",
    "nl" to "Dutch",
    "nn" to "Nynorsk, Norwegian",
    "no" to "Norwegian",
    "nr" to "South Ndebele",
    "nv" to "Navajo",
    "ny" to "Chichewa; Nyanja",
    "oc" to "Occitan (post 1500)",
    "oj" to "Ojibwa",
    "om" to "Oromo",
    "or" to "Oriya",
    "os" to "Ossetic",
    "pa" to "Punjabi",
    "pi" to "Pali",
    "pl" to "Polish",
    "ps" to "Pashto",
    "pt" to "Portuguese",
    "qu" to "Quechua",
    "rm" to "Romansh",
    "rn" to "Rundi",
    "ro" to "Romanian",
    "ru" to "Russian",
    "rw" to "Kinyarwanda",
    "sa" to "Sanskrit",
    "sc" to "Sardinian",
    "sd" to "Sindhi",
    "se" to "Northern Sami",
    "sg" to "Sango",
    "si" to "Sinhala",
    "sk" to "Slovak",
    "sl" to "Slovenian",
    "sm" to "Samoan",
    "sn" to "Shona",
    "so" to "Somali",
    "sq" to "Albanian",
    "sr" to "Serbian",
    "ss" to "Swati",
    "st" to "Sotho, Southern",
    "su" to "Sundanese",
    "sv" to "Swedish",
    "sw" to "Swahili",
    "ta" to "Tamil",
    "te" to "Telugu",
    "tg" to "Tajik",
    "th" to "Thai",
    "ti" to "Tigrinya",
    "tk" to "Turkmen",
    "tl" to "Tagalog",
    "tn" to "Tswana",
    "to" to "Tongan",
    "tr" to "Turkish",
    "ts" to "Tsonga",
    "tt" to "Tatar",
    "tw" to "Twi",
    "ty" to "Tahitian",
    "ug" to "Uighur",
    "uk" to "Ukrainian",
    "ur" to "Urdu",
    "uz" to "Uzbek",
    "ve" to "Venda",
    "vi" to "Vietnamese",
    "vo" to "Volapük",
    "wa" to "Walloon",
    "wo" to "Wolof",
    "xh" to "Xhosa",
    "yi" to "Yiddish",
    "yo" to "Yoruba",
    "za" to "Zhuang",
    "zh" to "Chinese",
    "zu" to "Zulu"
)