name: Publish Internal Release

on:
  push:
    branches:
      - master
    paths:
      - 'composeApp/**'
      - 'iosApp/**'
      - '.github/workflows/internal-release.yml'
      - '*.gradle.kts'
      - '*.properties'
      - 'gradle/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.10' ]
        jdk: [ 17 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk }}
          java-package: jdk
          cache: 'gradle'

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Prepare keystore
        run: echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > keystore.jks

      - name: Prepare Gradle secure file
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' >> local.properties

      - name: Build AAB
        id: build_aab
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: build_aab
          arguments: :composeApp:increaseVersionCode :composeApp:bundleRelease :composeApp:assembleRelease
          gradle-version: wrapper
          properties: |
            buildkonfig.flavor=production
      - name: Artifact
        id: artifact
        uses: actions/upload-artifact@v3
        with:
          name: Artifact
          path: |
            ./composeApp/build/outputs/bundle/release/composeApp-release.aab
            ./composeApp/build/outputs/apk/release/composeApp-release.apk

      - name: Commit version.properties
        id: commit_version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Increased Version Code
          file_pattern: 'version.properties'

      - name: Get version tag
        id: get_version_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/load_version.sh

      - name: Log version tag
        id: log_version_tag
        run: |
          echo "-- Shared --"
          echo "Version Code: $SHARED_VERSION_NAME"
          echo "-- --- --"
          echo ""
          echo "-- Android --"
          echo "Version Code: $ANDROID_VERSION_CODE"
          echo "Version Name: $ANDROID_VERSION_NAME"
          echo "IAUP: $IN_APP_UPDATE_PRIORITY"
          echo "-- --- --"
          echo ""
          echo "-- iOS --"
          echo "Version Name: $IOS_VERSION_NAME"
          echo "-- --- --"

      - name: Create GitHub release
        id: release_github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.SHARED_VERSION_NAME }}-${{ env.ANDROID_VERSION_NAME }}.${{ env.ANDROID_VERSION_CODE }}"
          prerelease: true
          title: "Android Development Build (${{ env.SHARED_VERSION_NAME }}-${{ env.ANDROID_VERSION_NAME }}.${{ env.ANDROID_VERSION_CODE }})"
          files: |
            ./composeApp/build/outputs/apk/release/composeApp-release.apk

      - name: Upload to Play Store
        id: upload_play_store
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_GOOGLE_CLOUD_JSON }}
          packageName: com.arnyminerz.filamagenta.android
          releaseFiles: ./composeApp/build/outputs/bundle/release/composeApp-release.aab
          track: internal
          inAppUpdatePriority: "${{ env.IN_APP_UPDATE_PRIORITY }}"
          status: completed
